// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvN43ke_o7RUOucNpwqhFfYfZaAZUVQuY',
    appId: '1:153885731876:web:0ddd4469d09cbe5ed6bcb1',
    messagingSenderId: '153885731876',
    projectId: 'my-web-base-bizproject',
    authDomain: 'my-web-base-bizproject.firebaseapp.com',
    storageBucket: 'my-web-base-bizproject.firebasestorage.app',
    measurementId: 'G-HV1Y9Y3MKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHL6VH-IFrkzKmSj5x6g78xolmdyIPw4',
    appId: '1:153885731876:android:a55c58f60e49313bd6bcb1',
    messagingSenderId: '153885731876',
    projectId: 'my-web-base-bizproject',
    storageBucket: 'my-web-base-bizproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2z2JTEIUkTEfM3YbftWIv0Y4XXt9fHXU',
    appId: '1:153885731876:ios:13cecdc2dff13965d6bcb1',
    messagingSenderId: '153885731876',
    projectId: 'my-web-base-bizproject',
    storageBucket: 'my-web-base-bizproject.firebasestorage.app',
    iosBundleId: 'com.awebbasebiz.app',
  );
}
